# Generated by Django 3.2.23 on 2023-12-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.EmailField(default='abc@example.com', max_length=254, unique=True),
        ),
    ]
