# Generated by Django 4.2.8 on 2023-12-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_category_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coverBook',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
