# Generated by Django 4.1.5 on 2023-11-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
