# Generated by Django 4.2.7 on 2023-11-30 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_novel_status_novel_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='novel',
        ),
        migrations.AddField(
            model_name='novel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.category'),
        ),
    ]
